Blue Newsletter for Liferay Portal
===================
Tomek Lipski <tlipski@bluesoft.net.pl>
:Author Initials: TL
:toc:
:icons:
:numbered:
:website: http://portal.bluesoft.net.pl

Info
------------
Blue Newsletter is a showcase of rapidly developed (less than two days of work), enterprise-friendly Vaadin portlet for
Liferay Enteprise Portal. Persistence has been provided by the Hibernate Framework.

Tutorial providing more implementation details and screenshots will soon be available at
http://portal.bluesoft.net.pl/web/tlipski/blog

The application delivers three independent portlets:
* newsletter subscription portlet - available to all users (of course depending on portlet instance configuration)
* newsletter sending portlet - used by content managers
* newsletter admin portlet - allowing admin users to define new newsletters

The dependency on *pl.net.bluesoft.util* maven package can be resolved by obtaining and
building https://github.com/tlipski/BlueSoft-Util.

The application has been deployed and tested on liferay-portal-6.0.6 running on top of tomcat-6.0.29.